name: FlutterNews
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^4.0.2
  share: ^0.6.0+1
  http: ^0.12.0
  bsev: ^0.8.0
  flutter_widget_from_html_core: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
      # - assets/place_holder.jpg
      # - assets/place_holder_2.jpg
      # - assets/place_holder_3.jpg
      - assets/itz_place_holder.png
      - assets/itz_place_holder_2.png
      - assets/itz_place_holder_3.png
      - assets/itz_place_holder_5.jpg
      - resources/lang/en.json
      - resources/lang/pt.json
  
  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-Regular.ttf
        - asset: fonts/Lora-Bold.ttf
